Update jdbdump and jdbimp version numbers and add DDEV project directory checks

diff --git a/src/Scripts/jdbimp b/src/Scripts/jdbimp
--- a/src/Scripts/jdbimp
+++ b/src/Scripts/jdbimp
@@ -12,9 +12,11 @@
 # 1.1 Added auto-detection of db.sql and db.sql.gz
 # 1.2 Added exit code check for ddev import-db
 # 1.3 Added -v verbose option
+# 1.4 Added check if users starts jdbdump in a DDEV project directory
+
 
 # version
-VERSION=1.3
+VERSION=1.4
 
 # general variables
 MYNAME=$(basename "$0")
@@ -80,6 +82,12 @@ if [[ -z "${DUMPFILE}" ]]; then
 fi
 
 showmessage "${MYNAME} ${VERSION}"
+
+# Check if .ddev directory file exists
+if [ ! -d ".ddev" ]; then
+    echo "Error: this directory is not a DDEV project, are you at the root of the website?" >&2
+    exit 1
+fi
 
 # Check if database dump exists
 if [[ ! -e "${DUMPFILE}" ]]; then
