Update jdbimp version to 1.5 and enhance error messages for DDEV project checks

diff --git a/src/Scripts/jdbimp b/src/Scripts/jdbimp
--- a/src/Scripts/jdbimp
+++ b/src/Scripts/jdbimp
@@ -13,8 +13,9 @@
 # 1.2 Added exit code check for ddev import-db
 # 1.3 Added -v verbose option
 # 1.4 Added check if users starts jdbdump in a DDEV project directory
+# 1.5 Add project name to dump filename if not specified in config
 
-VERSION=1.4
+VERSION=1.5
 
 # Name of this script
 MYNAME=$(basename "$0")
@@ -62,10 +63,20 @@ while getopts "f:vsh" opt; do
     esac
 done
 
+showmessage "${MYNAME} ${VERSION}"
+
+# Check if .ddev directory file exists
+if [ ! -d ".ddev" ]; then
+    echo "Error: this directory is not a DDEV project, are you at the root of the website?" >&2
+    exit 1
+fi
+
+WEBSITE_NAME=$(basename "$PWD")
+
 # If no custom dump file specified, auto-detect default dump file
 if [[ -z "${DUMPFILE}" ]]; then
-    IMPORTFILE="db.sql"
-    IMPORTFILECOMPRESSED="db.sql.gz"
+    IMPORTFILE="${WEBSITE_NAME}-db.sql"
+    IMPORTFILECOMPRESSED="${WEBSITE_NAME}-db.sql.gz"
     if [[ -e "${IMPORTFILE}" && -e "${IMPORTFILECOMPRESSED}" ]]; then
         echo "Error: Both ${IMPORTFILE} and ${IMPORTFILECOMPRESSED} exist. Please specify which file to import with -f."
         exit 1
@@ -74,17 +85,9 @@ if [[ -z "${DUMPFILE}" ]]; then
     elif [[ -e "${IMPORTFILECOMPRESSED}" ]]; then
         DUMPFILE="${IMPORTFILECOMPRESSED}"
     else
-        echo "Error: No database dump file found (db.sql or db.sql.gz)."
+        echo "Error: No database dump file found (${WEBSITE_NAME}-db.sql or ${WEBSITE_NAME}-db.sql.gz)."
         exit 1
     fi
-fi
-
-showmessage "${MYNAME} ${VERSION}"
-
-# Check if .ddev directory file exists
-if [ ! -d ".ddev" ]; then
-    echo "Error: this directory is not a DDEV project, are you at the root of the website?" >&2
-    exit 1
 fi
 
 # Check if database dump exists
